apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-app
        image: nginxdemos/hello
        ports:
        - containerPort: 80
          name: web-port

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    apps: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: nginx
